logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql: TRACE

spring:
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:../data/db
    username: sa
    password:
    driverClassName: org.h2.Driver
